format:
  html:
    toc: true
    toc-depth: 4
    theme: [cosmo, notebooks/custom.scss]
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: Stats With Clojure
  chapters: [index.qmd, stats_with_clojure.about_this_book.qmd, stats_with_clojure.getting_this_book.qmd, stats_with_clojure.setting_things_up.qmd, stats_with_clojure.basic_statistics.qmd, stats_with_clojure.visualization.qmd, stats_with_clojure.charts.qmd, stats_with_clojure.bibliography.qmd]
